/**
 * Default keybinding configuration.
 */

import type { KeybindingsConfig } from './types';

export const DEFAULT_KEYBINDINGS: KeybindingsConfig = {
  prefixKey: 'ctrl+b',
  prefixTimeoutMs: 2000,
  normal: {
    'alt+h': 'pane.focus.west',
    'alt+j': 'pane.focus.south',
    'alt+k': 'pane.focus.north',
    'alt+l': 'pane.focus.east',
    'alt+m': 'mode.move',
    'alt+n': 'pane.new',
    'alt+s': 'session.picker.toggle',
    'alt+t': 'template.overlay.toggle',
    'alt+g': 'aggregate.toggle',
    'alt+f': 'search.open',
    'alt+p': 'command.palette.toggle',
    'alt+[': 'layout.cycle.prev',
    'alt+]': 'layout.cycle.next',
    'alt+z': 'pane.zoom',
    'alt+x': 'pane.close',
    'alt+-': 'pane.split.horizontal',
    'alt+\\': 'pane.split.vertical',
    ...Object.fromEntries(
      Array.from({ length: 9 }, (_, i) => [`alt+${i + 1}`, `workspace.switch.${i + 1}`])
    ),
  },
  prefix: {
    'h': 'pane.focus.west',
    'j': 'pane.focus.south',
    'k': 'pane.focus.north',
    'l': 'pane.focus.east',
    'm': 'mode.move',
    'n': 'pane.new',
    'enter': 'pane.new',
    '\\': 'pane.split.vertical',
    '-': 'pane.split.horizontal',
    'x': 'pane.close',
    'v': 'layout.mode.vertical',
    'shift+h': 'layout.mode.horizontal',
    't': 'layout.mode.stacked',
    'shift+t': 'template.overlay.toggle',
    's': 'session.picker.toggle',
    'g': 'aggregate.toggle',
    '/': 'search.open',
    ':': 'command.palette.toggle',
    'z': 'pane.zoom',
    ']': 'clipboard.paste',
    'p': 'clipboard.paste',
    '`': 'console.toggle',
    'q': 'app.quit',
    'd': 'app.detach',
    'escape': 'mode.cancel',
    ...Object.fromEntries(
      Array.from({ length: 9 }, (_, i) => [`${i + 1}`, `workspace.switch.${i + 1}`])
    ),
  },
  move: {
    'h': 'pane.move.west',
    'j': 'pane.move.south',
    'k': 'pane.move.north',
    'l': 'pane.move.east',
    'escape': 'mode.cancel',
  },
  search: {
    'ctrl+n': 'search.next',
    'ctrl+p': 'search.prev',
    'enter': 'search.confirm',
    'escape': 'search.cancel',
    'backspace': 'search.delete',
  },
  commandPalette: {
    'down': 'command.palette.down',
    'up': 'command.palette.up',
    'enter': 'command.palette.confirm',
    'escape': 'command.palette.close',
    'backspace': 'command.palette.delete',
  },
  templateOverlay: {
    apply: {
      'escape': 'template.close',
      'tab': 'template.tab.save',
      'down': 'template.list.down',
      'up': 'template.list.up',
      'enter': 'template.apply',
      'ctrl+x': 'template.delete',
      'ctrl+d': 'template.delete',
    },
    save: {
      'escape': 'template.close',
      'tab': 'template.tab.apply',
      'enter': 'template.save',
      'backspace': 'template.save.delete',
    },
  },
  aggregate: {
    list: {
      'down': 'aggregate.list.down',
      'up': 'aggregate.list.up',
      'enter': 'aggregate.list.preview',
      'tab': 'aggregate.list.jump',
      'alt+escape': 'aggregate.list.close',
      'alt+a': 'aggregate.list.toggle.scope',
      'alt+x': 'aggregate.kill',
      'backspace': 'aggregate.list.delete',
    },
    preview: {
      'alt+escape': 'aggregate.preview.exit',
      'alt+f': 'aggregate.preview.search',
      'alt+x': 'aggregate.kill',
    },
    search: {
      'enter': 'aggregate.search.confirm',
      'escape': 'aggregate.search.cancel',
      'ctrl+n': 'aggregate.search.next',
      'ctrl+p': 'aggregate.search.prev',
      'backspace': 'aggregate.search.delete',
    },
    prefix: {
      'q': 'aggregate.prefix.quit',
      'd': 'aggregate.prefix.detach',
      'escape': 'aggregate.prefix.exit',
      '/': 'aggregate.prefix.search',
    },
  },
  sessionPicker: {
    list: {
      'escape': 'session.picker.close',
      'down': 'session.picker.down',
      'up': 'session.picker.up',
      'enter': 'session.picker.select',
      'backspace': 'session.picker.filter.delete',
      'ctrl+n': 'session.picker.create',
      'ctrl+r': 'session.picker.rename',
      'ctrl+x': 'session.picker.delete',
      'ctrl+d': 'session.picker.delete',
    },
    rename: {
      'escape': 'session.picker.rename.cancel',
      'enter': 'session.picker.rename.confirm',
      'backspace': 'session.picker.rename.delete',
    },
  },
  confirmation: {
    'escape': 'confirm.cancel',
    'enter': 'confirm.accept',
    'left': 'confirm.focus.confirm',
    'h': 'confirm.focus.confirm',
    'right': 'confirm.focus.cancel',
    'l': 'confirm.focus.cancel',
    'tab': 'confirm.focus.cancel',
  },
};
